version: "3"

services:
  backend-gestion-envios:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-gestion-envios-image
    container_name: backend-gestion-envios
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
